
services:
  mongo:
    image: mongo:7
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: SidhaReporting
    volumes:
      - mongo-data:/data/db
    networks:
      - fullstack-network

  server:
    build: ./backend
    container_name: express-server
    ports:
      - "8000:8000"
    networks:
      - fullstack-network
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      FRONTEND_URL: http://localhost:5173

  client:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000/apis/v1/
    container_name: react-client
    ports:
      - "5173:3000"
    networks:
      - fullstack-network
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  fullstack-network:
    driver: bridge